// SPDX-License-Identifier: AGPL-3.0-or-later

//! Network-tool hook ingestion on the daemon side (S17.9).
//!
//! Mirrors [`crate::pkg`], [`crate::env_track`], and
//! [`crate::svc_track`]: an in-memory Pre stash keyed by
//! `(tool, pid, scope_hint)`, Post pairs and emits a diff.
//! Journal-write under `(session, seq)` is DR-41 (same family as
//! DR-25 / DR-32 / DR-36).
//!
//! Unlike the service tracker, **we don't parse the state_raw on
//! the daemon side**. The dump is opaque bytes; the executor pipes
//! it back through the tool's own restore command. Equality comes
//! from byte comparison.

use std::collections::HashMap;
use std::sync::Mutex;
use std::time::{Duration, Instant};

use shit_proto::{NetEventReq, NetToolWire};

pub const PRE_STASH_TTL: Duration = Duration::from_secs(300);

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct NetKey {
    pub tool: NetToolWire,
    pub pid: u32,
    pub scope_hint: String,
}

#[derive(Debug, Clone)]
pub struct NetPre {
    pub state_raw: Vec<u8>,
    pub verb: String,
    pub ts: Instant,
}

pub struct NetPreStash {
    inner: Mutex<HashMap<NetKey, NetPre>>,
}

impl NetPreStash {
    pub fn new() -> Self {
        Self {
            inner: Mutex::new(HashMap::new()),
        }
    }
    pub fn insert(&self, key: NetKey, pre: NetPre) {
        self.inner.lock().unwrap().insert(key, pre);
    }
    pub fn take(&self, key: &NetKey) -> Option<NetPre> {
        self.inner.lock().unwrap().remove(key)
    }
    pub fn sweep_expired(&self) -> usize {
        let mut g = self.inner.lock().unwrap();
        let cutoff = Instant::now()
            .checked_sub(PRE_STASH_TTL)
            .unwrap_or_else(Instant::now);
        let before = g.len();
        g.retain(|_, e| e.ts >= cutoff);
        before - g.len()
    }
    #[cfg(test)]
    pub fn len(&self) -> usize {
        self.inner.lock().unwrap().len()
    }
}

impl Default for NetPreStash {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PostOutcome {
    /// No Pre stashed for this (tool, pid, scope_hint) — orphan.
    Orphan,
    /// Pre and Post bytes are identical.
    Unchanged,
    /// Pre and Post bytes differ.
    Changed {
        before_len: usize,
        after_len: usize,
        verb: String,
    },
}

pub fn handle(stash: &NetPreStash, req: NetEventReq) -> PostOutcome {
    let key = NetKey {
        tool: req.tool,
        pid: req.pid,
        scope_hint: req.scope_hint.clone(),
    };
    match req.phase {
        shit_proto::PkgPhase::Pre => {
            tracing::debug!(
                tool = req.tool.as_str(),
                pid = req.pid,
                scope = %req.scope_hint,
                verb = %req.verb,
                bytes = req.state_raw.len(),
                "net-pre stashed"
            );
            stash.insert(
                key,
                NetPre {
                    state_raw: req.state_raw,
                    verb: req.verb,
                    ts: Instant::now(),
                },
            );
            PostOutcome::Orphan
        }
        shit_proto::PkgPhase::Post => {
            let Some(pre) = stash.take(&key) else {
                tracing::warn!(
                    tool = req.tool.as_str(),
                    pid = req.pid,
                    "net-post with no matching pre; dropping (orphan)"
                );
                return PostOutcome::Orphan;
            };
            if pre.state_raw == req.state_raw {
                tracing::debug!(
                    tool = req.tool.as_str(),
                    pid = req.pid,
                    "net-post unchanged; dropping"
                );
                return PostOutcome::Unchanged;
            }
            tracing::info!(
                tool = req.tool.as_str(),
                pid = req.pid,
                verb = %pre.verb,
                before_len = pre.state_raw.len(),
                after_len = req.state_raw.len(),
                "net-post changed (DR-41 will journal the diff)"
            );
            PostOutcome::Changed {
                before_len: pre.state_raw.len(),
                after_len: req.state_raw.len(),
                verb: pre.verb,
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use shit_proto::PkgPhase;

    fn req(phase: PkgPhase, pid: u32, verb: &str, raw: &[u8]) -> NetEventReq {
        NetEventReq {
            tool: NetToolWire::Iptables,
            phase,
            verb: verb.into(),
            scope_hint: "filter".into(),
            pid,
            uid: 1000,
            state_raw: raw.to_vec(),
        }
    }

    #[test]
    fn pre_post_unchanged_when_bytes_match() {
        let stash = NetPreStash::new();
        let raw = b"# generated by iptables-save\n*filter\n";
        let _ = handle(&stash, req(PkgPhase::Pre, 42, "-A", raw));
        let outcome = handle(&stash, req(PkgPhase::Post, 42, "-A", raw));
        assert_eq!(outcome, PostOutcome::Unchanged);
        assert_eq!(stash.len(), 0);
    }

    #[test]
    fn pre_post_changed_when_bytes_differ() {
        let stash = NetPreStash::new();
        let _ = handle(&stash, req(PkgPhase::Pre, 42, "-A", b"before"));
        let outcome = handle(&stash, req(PkgPhase::Post, 42, "-A", b"after-bytes"));
        match outcome {
            PostOutcome::Changed {
                before_len,
                after_len,
                verb,
            } => {
                assert_eq!(before_len, 6);
                assert_eq!(after_len, 11);
                assert_eq!(verb, "-A");
            }
            other => panic!("expected Changed, got {other:?}"),
        }
    }

    #[test]
    fn orphan_post_is_dropped() {
        let stash = NetPreStash::new();
        let outcome = handle(&stash, req(PkgPhase::Post, 99, "-A", b"x"));
        assert_eq!(outcome, PostOutcome::Orphan);
    }

    #[test]
    fn sweep_evicts_old_entries() {
        let stash = NetPreStash::new();
        let key = NetKey {
            tool: NetToolWire::Iptables,
            pid: 42,
            scope_hint: "filter".into(),
        };
        {
            let mut g = stash.inner.lock().unwrap();
            g.insert(
                key,
                NetPre {
                    state_raw: vec![],
                    verb: "-A".into(),
                    ts: Instant::now()
                        .checked_sub(PRE_STASH_TTL + Duration::from_secs(1))
                        .expect("clock subtraction"),
                },
            );
        }
        assert_eq!(stash.sweep_expired(), 1);
        assert_eq!(stash.len(), 0);
    }
}
