[package]
name = "shit-helper"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "shit-helper"
path = "src/main.rs"

[build-dependencies]
vergen-gitcl = { workspace = true }

[dependencies]
shit-proto = { workspace = true }
shit-capture = { workspace = true }
nix = { workspace = true }
libc = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
seccompiler = "0.5"
bitflags = { workspace = true }
crossbeam-channel = "0.5"

[dev-dependencies]
tempfile = "3.10"
