#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# AR04.4 smoke — `gh release delete <tag>; shit undo` recreates the
# release from the captured JSON metadata.
#
# Auth: uses GITHUB_TOKEN that GHA injects automatically into every
# job. Scope is the running repo (tenseleyFlow/shit), with contents:
# write per the workflow's permissions block.
#
# Tag scheme: `shit-smoke-${GITHUB_RUN_ID:-local}-$$` so concurrent
# CI runs don't collide and locally-invoked runs use a PID suffix.
# Smoke trap-cleanup deletes the release on exit (success OR failure)
# so the prod repo's release list doesn't accumulate cruft.
#
# Exercises (DR-CR-06 cloud-event path, gh direction):
#   1. Pre-state: `gh release create <tag>` (NOT through hooks).
#   2. Helper's prepare_gh: `gh release view <tag> --json ...`
#      captures the metadata.
#   3. Daemon journals CaptureEvent::GhOp { ReleaseDelete, json }.
#   4. The real gh proceeds to delete the release.
#   5. `shit undo --yes` walks captured_json → InverseOp::GhReverse →
#      build_reverse synthesizes `gh release create <tag> --title X
#      --notes-file -` with the captured body piped on stdin.
#   6. Post-undo: `gh release view <tag>` finds the release with
#      the same title.

# shellcheck disable=SC2154
SHIT_REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
export SHIT_REPO_ROOT
# shellcheck source=lib.sh
source "${SHIT_REPO_ROOT}/tests/smoke/lib.sh"

if [ "$(uname -s)" != "Linux" ]; then
    smoke_log "SKIP: gh-release-delete-undo-linux is Linux-only (uname=$(uname -s))"
    exit 0
fi
if ! command -v gh >/dev/null 2>&1; then
    smoke_log "SKIP: gh not on PATH"
    exit 0
fi
if [ -z "${GITHUB_TOKEN:-}" ] && [ -z "${GH_TOKEN:-}" ]; then
    smoke_log "SKIP: GITHUB_TOKEN/GH_TOKEN not set (smoke needs repo auth)"
    exit 0
fi
# gh reads either; normalize to GH_TOKEN since gh prefers it.
export GH_TOKEN="${GH_TOKEN:-${GITHUB_TOKEN}}"

# gh needs a repo context. In CI it auto-detects from GITHUB_REPOSITORY;
# locally fall back to the git origin's slug.
REPO="${GITHUB_REPOSITORY:-}"
if [ -z "${REPO}" ]; then
    REPO="$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || true)"
fi
if [ -z "${REPO}" ]; then
    smoke_log "SKIP: cannot determine repo (no GITHUB_REPOSITORY env and no git origin)"
    exit 0
fi
export GH_REPO="${REPO}"

HELPER_BIN="${SHIT_SMOKE_BIN_DIR}/shit-helper"
SHIT_BIN="${SHIT_SMOKE_BIN_DIR}/shit"
[ -x "${HELPER_BIN}" ] || smoke_fail "shit-helper missing at ${HELPER_BIN}"
[ -x "${SHIT_BIN}" ] || smoke_fail "shit missing at ${SHIT_BIN}"
export SHIT_HELPER_BIN="${HELPER_BIN}"

TAG="shit-smoke-${GITHUB_RUN_ID:-local}-$$"
TITLE="shit smoke ${TAG}"
BODY="Generated by tests/smoke/gh-release-delete-undo-linux.sh at $(date -u +%FT%TZ). Auto-deleted by smoke trap."

cleanup_release() {
    # Try both pre- and post-undo paths since either could leave a
    # release lying around. SHIT_DURING_UNDO=1 bypasses our own hook.
    SHIT_DURING_UNDO=1 gh release delete "${TAG}" --yes --cleanup-tag \
        >/dev/null 2>&1 || true
}
trap 'cleanup_release' EXIT

smoke_log "pre-state: gh release create ${TAG} on ${REPO}"
gh release create "${TAG}" \
    --repo "${REPO}" \
    --title "${TITLE}" \
    --notes "${BODY}" \
    >"${SHIT_SMOKE_TMP}/gh-precreate.log" 2>&1 \
    || {
        sed 's/^/    /' "${SHIT_SMOKE_TMP}/gh-precreate.log" >&2
        smoke_fail "gh release create ${TAG} failed"
    }

# Confirm baseline.
if ! gh release view "${TAG}" --repo "${REPO}" >/dev/null 2>&1; then
    smoke_fail "release ${TAG} not visible after create"
fi
smoke_log "pre-state: release ${TAG} exists"

smoke_start_shitd

smoke_log "installing cloud-hooks"
"${SHIT_BIN}" cloud-hooks install >"${SHIT_SMOKE_TMP}/hooks-install.log" 2>&1 \
    || smoke_fail "cloud-hooks install failed"
HOOKS_BIN="${XDG_CONFIG_HOME}/shit/bin"
[ -x "${HOOKS_BIN}/gh" ] || smoke_fail "gh wrapper missing"
export PATH="${HOOKS_BIN}:${PATH}"
export PATH="${SHIT_SMOKE_BIN_DIR}:${PATH}"

resolved_gh="$(command -v gh)"
case "${resolved_gh}" in
    "${HOOKS_BIN}/gh") smoke_log "gh resolves to wrapper: ${resolved_gh}" ;;
    *) smoke_fail "expected gh to resolve to wrapper, got ${resolved_gh}" ;;
esac

SESSION="$(python3 -c 'import uuid; print(uuid.uuid4())')"
PID="$$"
smoke_log "SessionOpen session=${SESSION} pid=${PID}"
"${SHIT_BIN}" hook-send session-open \
    --session "${SESSION}" --pid "${PID}" --shell bash \
    --tty "$(tty 2>/dev/null || echo /dev/null)" \
    --sock "${SHIT_HOOK_SOCK}"

smoke_log "PreExec seq=1 pid=${PID}"
"${SHIT_BIN}" hook-send pre-exec \
    --session "${SESSION}" --seq 1 --pid "${PID}" \
    --cwd "$(pwd)" --shell bash --sock "${SHIT_HOOK_SOCK}"

smoke_log "gh release delete ${TAG} (via wrapper)"
export SHIT_HOOK_DEBUG=1
if ! gh release delete "${TAG}" --yes >"${SHIT_SMOKE_TMP}/gh-delete.log" 2>&1; then
    smoke_log "gh-delete.log:"
    sed 's/^/    /' "${SHIT_SMOKE_TMP}/gh-delete.log" >&2
    smoke_fail "gh release delete ${TAG} exited non-zero"
fi
smoke_log "gh-delete.log (informational; delete succeeded):"
sed 's/^/    /' "${SHIT_SMOKE_TMP}/gh-delete.log" >&2

# Confirm gone.
if gh release view "${TAG}" --repo "${REPO}" >/dev/null 2>&1; then
    smoke_fail "release ${TAG} still present after delete"
fi
smoke_log "post-delete: release ${TAG} gone"

smoke_log "PostExec seq=1"
"${SHIT_BIN}" hook-send post-exec \
    --session "${SESSION}" --seq 1 --exit-code 0 --sock "${SHIT_HOOK_SOCK}"

smoke_wait_for_event "discriminant = 'GhOp'" 1 10

smoke_log "running: shit undo --yes"
"${SHIT_BIN}" undo --yes 2>&1 | tee "${SHIT_SMOKE_TMP}/undo.log" || {
    smoke_log "undo log:"
    sed 's/^/    /' "${SHIT_SMOKE_TMP}/undo.log" >&2
    smoke_fail "shit undo --yes exited non-zero"
}

# Post-undo: release back with the same title. body may differ
# slightly (github CLI normalizes whitespace) — title is the reliable
# identifier.
if ! SHIT_DURING_UNDO=1 gh release view "${TAG}" --repo "${REPO}" >/dev/null 2>&1; then
    smoke_log "undo log:"
    sed 's/^/    /' "${SHIT_SMOKE_TMP}/undo.log" >&2
    smoke_fail "release ${TAG} not recreated by undo — gh release create didn't run"
fi

post_title="$(SHIT_DURING_UNDO=1 gh release view "${TAG}" --repo "${REPO}" --json name --jq .name 2>/dev/null)"
if [ "${post_title}" != "${TITLE}" ]; then
    smoke_log "title drift: expected '${TITLE}' got '${post_title}'"
    smoke_fail "release title not preserved across delete/undo"
fi
smoke_log "post-undo: release ${TAG} recreated with title '${post_title}' (delete→undo round-trip confirmed)"

smoke_log "session close"
"${SHIT_BIN}" hook-send session-close \
    --session "${SESSION}" --sock "${SHIT_HOOK_SOCK}"

smoke_log "PASS: gh-release-delete-undo-linux (${TAG} deleted → undo recreated)"
