[package]
name = "shit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "shit"
path = "src/main.rs"

[build-dependencies]
vergen-gitcl = { workspace = true }

[dependencies]
shit-proto = { workspace = true }
shit-shell = { workspace = true }
shit-capture = { workspace = true }
shit-planner = { workspace = true }
shit-desc = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
clap_mangen = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
libc = { workspace = true }

[dev-dependencies]
tempfile = "3.10"
