// SPDX-License-Identifier: AGPL-3.0-or-later

//! `shit config` — read/write the user's config file at
//! `$XDG_CONFIG_HOME/shit/config.toml`.
//!
//! Subcommands:
//! - `get <key>` — print one key.
//! - `set <key> <value>` — write one key.
//! - `edit` — open `$EDITOR` on the file (fall back to printing the file path).
//! - `list` — print all keys.
//!
//! Stage 1: actually creates / reads / writes the file using a simple
//! flat key=value layout (no nested tables). The schema gets nailed
//! down in a follow-up audit doc; for now everything is a string.

use std::path::PathBuf;

use clap::{Args, Subcommand};

use crate::exitcode::{CliError, GENERIC_FAILURE};

#[derive(Debug, Clone, Args)]
pub struct ConfigArgs {
    #[command(subcommand)]
    pub action: ConfigCmd,
}

#[derive(Debug, Clone, Subcommand)]
pub enum ConfigCmd {
    Get { key: String },
    Set { key: String, value: String },
    Edit,
    List,
}

pub fn run(args: ConfigArgs) -> Result<(), CliError> {
    let path = config_path()?;
    match args.action {
        ConfigCmd::Get { key } => {
            let val = read_key(&path, &key)?;
            match val {
                Some(v) => println!("{v}"),
                None => {
                    return Err(CliError::fail(
                        GENERIC_FAILURE,
                        format!("key not set: {key}"),
                    ));
                }
            }
        }
        ConfigCmd::Set { key, value } => {
            write_key(&path, &key, &value)?;
        }
        ConfigCmd::Edit => {
            edit_config(&path)?;
        }
        ConfigCmd::List => {
            let pairs = read_all(&path)?;
            if pairs.is_empty() {
                println!("(empty config at {})", path.display());
            } else {
                for (k, v) in pairs {
                    println!("{k} = {v}");
                }
            }
        }
    }
    Ok(())
}

fn config_path() -> Result<PathBuf, CliError> {
    let base = if let Some(d) = std::env::var_os("XDG_CONFIG_HOME") {
        PathBuf::from(d)
    } else if let Some(h) = std::env::var_os("HOME") {
        PathBuf::from(h).join(".config")
    } else {
        return Err(CliError::fail(
            GENERIC_FAILURE,
            "neither XDG_CONFIG_HOME nor HOME set",
        ));
    };
    Ok(base.join("shit").join("config.toml"))
}

fn ensure_parent(path: &std::path::Path) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    Ok(())
}

/// Very small "TOML-flavored" reader: one `key = "value"` per line,
/// `#` for comments. We parse what we wrote; not a general TOML
/// reader. A real TOML dependency lands when nested tables exist.
fn read_all(path: &std::path::Path) -> Result<Vec<(String, String)>, CliError> {
    if !path.exists() {
        return Ok(vec![]);
    }
    let body = std::fs::read_to_string(path)?;
    let mut out = Vec::new();
    for raw in body.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((k, v)) = line.split_once('=') else {
            continue;
        };
        let k = k.trim();
        let v = v.trim().trim_matches('"');
        out.push((k.to_string(), v.to_string()));
    }
    Ok(out)
}

fn read_key(path: &std::path::Path, key: &str) -> Result<Option<String>, CliError> {
    let all = read_all(path)?;
    Ok(all.into_iter().find(|(k, _)| k == key).map(|(_, v)| v))
}

fn write_key(path: &std::path::Path, key: &str, value: &str) -> Result<(), CliError> {
    let mut pairs = read_all(path)?;
    if let Some(existing) = pairs.iter_mut().find(|(k, _)| k == key) {
        existing.1 = value.to_string();
    } else {
        pairs.push((key.to_string(), value.to_string()));
    }
    let mut body = String::new();
    body.push_str("# shit config — auto-generated by `shit config set`\n");
    body.push_str("# (lines with `=` are key/value pairs; nested tables not yet supported)\n");
    for (k, v) in &pairs {
        body.push_str(&format!("{k} = \"{v}\"\n"));
    }
    ensure_parent(path)?;
    std::fs::write(path, body)?;
    Ok(())
}

fn edit_config(path: &std::path::Path) -> Result<(), CliError> {
    ensure_parent(path)?;
    if !path.exists() {
        std::fs::write(path, "# shit config — empty\n")?;
    }
    let editor = std::env::var("EDITOR")
        .or_else(|_| std::env::var("VISUAL"))
        .ok();
    match editor {
        Some(e) if !e.trim().is_empty() => {
            let status = std::process::Command::new(&e).arg(path).status()?;
            if !status.success() {
                return Err(CliError::fail(
                    GENERIC_FAILURE,
                    format!("editor `{e}` exited with status {status}"),
                ));
            }
        }
        _ => {
            // No editor set — fall back to printing the path. The user
            // can `vim "$(shit config edit)"` from there if they want.
            println!("{}", path.display());
        }
    }
    Ok(())
}
