// SPDX-License-Identifier: AGPL-3.0-or-later

//! AU08 — sudoers snippet generation for the seamless dev loop.
//!
//! Background: smokes pre-flight on `getcap` of the helper binary,
//! cargo rebuilds strip those caps, and `sudo setcap` requires a
//! password by default. Pasting a NOPASSWD line into
//! `/etc/sudoers.d/shit-dev` (or `security.sudo.extraRules` on
//! NixOS) lets `tools/linux/post-build-setcap.sh` reapply caps
//! without prompting.
//!
//! This module renders that snippet. The exact paths depend on
//! where the user typically rebuilds — `~/.cargo/bin/shit-helper`
//! for `cargo install --path crates/shit-helper`, the workspace
//! `target/{debug,release}/shit-helper` for `cargo build`. We list
//! all plausible paths so one snippet covers both dev styles.

use std::path::PathBuf;

/// Distinct sudoers grammars the snippet generator emits. Most distros
/// share the `sudoers(5)` syntax (Generic). NixOS uses its own Nix-
/// configuration form for `security.sudo.extraRules`, which is
/// declarative and survives `nixos-rebuild switch`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SudoersTarget {
    Generic,
    NixOS,
}

impl std::str::FromStr for SudoersTarget {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_ascii_lowercase().as_str() {
            "generic" | "debian" | "fedora" | "rhel" | "arch" => Ok(Self::Generic),
            "nixos" | "nix" => Ok(Self::NixOS),
            other => Err(format!(
                "unknown sudoers target {other:?}; expected 'generic' or 'nixos'"
            )),
        }
    }
}

/// Render a paste-ready sudoers snippet for the given target. The
/// snippet covers every plausible helper-binary path on the host
/// (workspace debug/release + cargo install path + the system
/// install path) so one paste covers all dev styles.
pub fn emit_sudoers_snippet(target: SudoersTarget) -> String {
    let user = current_user();
    let setcap = discover_setcap();
    let paths = discover_helper_binary_paths();
    match target {
        SudoersTarget::Generic => render_generic(&user, &setcap, &paths),
        SudoersTarget::NixOS => render_nixos(&user, &setcap, &paths),
    }
}

fn current_user() -> String {
    std::env::var("USER").unwrap_or_else(|_| "$USER".into())
}

fn discover_setcap() -> String {
    // Prefer PATH lookup (covers NixOS where setcap lives under
    // /run/current-system/sw/bin); fall back to the FHS path.
    if let Ok(path) = std::env::var("PATH") {
        for dir in path.split(':') {
            let candidate = PathBuf::from(dir).join("setcap");
            if candidate.is_file() {
                return candidate.display().to_string();
            }
        }
    }
    "/usr/sbin/setcap".to_string()
}

/// Enumerate plausible helper-binary paths. Order matters for the
/// human reader (most-likely-used first) but doesn't affect sudoers
/// semantics — each path is a separate command spec.
pub fn discover_helper_binary_paths() -> Vec<PathBuf> {
    let mut paths = Vec::new();

    let home = std::env::var("HOME").unwrap_or_else(|_| "$HOME".into());

    // cargo build (workspace) — what `make dev` / `make build` produce.
    if let Ok(cwd) = std::env::current_dir() {
        paths.push(cwd.join("target/debug/shit-helper"));
        paths.push(cwd.join("target/release/shit-helper"));
    } else {
        paths.push(PathBuf::from("./target/debug/shit-helper"));
        paths.push(PathBuf::from("./target/release/shit-helper"));
    }

    // cargo install --path crates/shit-helper.
    paths.push(PathBuf::from(format!("{home}/.cargo/bin/shit-helper")));

    // System install (packaged .deb/.rpm or `make install`).
    paths.push(PathBuf::from("/usr/local/bin/shit-helper"));
    paths.push(PathBuf::from("/usr/bin/shit-helper"));

    paths
}

const CAPS: &str = "cap_sys_admin,cap_bpf,cap_perfmon+ep";

fn render_generic(user: &str, setcap: &str, paths: &[PathBuf]) -> String {
    // sudoers permits one Cmnd_Spec per line. A single NOPASSWD spec
    // can list a comma-separated set of commands sharing the same
    // permission. Each command spec is `<full-path> <args>`. setcap
    // doesn't accept globs, so list each helper path explicitly.
    let mut cmds = String::new();
    for (i, p) in paths.iter().enumerate() {
        if i > 0 {
            cmds.push_str(", \\\n        ");
        }
        cmds.push_str(&format!("{setcap} {CAPS} {}", p.display()));
    }

    format!(
        "# /etc/sudoers.d/shit-dev\n\
         # AU08 — NOPASSWD for `setcap` on the shit-helper binary so\n\
         # cargo rebuilds re-apply caps without prompting. Generated by\n\
         # `shit doctor --emit-sudoers-snippet`.\n\
         #\n\
         # Install:\n\
         #   sudo visudo -f /etc/sudoers.d/shit-dev   (then paste below)\n\
         #   sudo chmod 0440 /etc/sudoers.d/shit-dev\n\
         #\n\
         # Then in your shell rc:\n\
         #   export SHIT_AUTO_SETCAP=1\n\
         {user} ALL=(root) NOPASSWD: {cmds}\n"
    )
}

fn render_nixos(user: &str, setcap: &str, paths: &[PathBuf]) -> String {
    // NixOS users put this in configuration.nix and run
    // `nixos-rebuild switch`. The extraRules form mirrors
    // sudoers' Cmnd_Spec list semantics.
    let mut cmds = String::new();
    for p in paths {
        cmds.push_str(&format!(
            "        {{\n          command = \"{setcap} {CAPS} {}\";\n          options = [ \"NOPASSWD\" ];\n        }}\n",
            p.display()
        ));
    }

    format!(
        "# AU08 — NOPASSWD for `setcap` on the shit-helper binary so\n\
         # cargo rebuilds re-apply caps without prompting. Generated by\n\
         # `shit doctor --emit-sudoers-snippet --target nixos`.\n\
         #\n\
         # Paste into configuration.nix, then `sudo nixos-rebuild switch`.\n\
         # Then in your shell rc:\n\
         #   export SHIT_AUTO_SETCAP=1\n\
         security.sudo.extraRules = [\n\
         \x20\x20{{\n\
         \x20\x20\x20\x20users = [ \"{user}\" ];\n\
         \x20\x20\x20\x20commands = [\n\
         {cmds}\
         \x20\x20\x20\x20];\n\
         \x20\x20}}\n\
         ];\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generic_snippet_contains_setcap_invocations_for_each_path() {
        let snip = emit_sudoers_snippet(SudoersTarget::Generic);
        assert!(snip.contains("NOPASSWD"));
        assert!(snip.contains("cap_sys_admin,cap_bpf,cap_perfmon+ep"));
        // Should mention both the cargo workspace target paths and the
        // ~/.cargo/bin path so one paste covers both dev styles.
        assert!(snip.contains("target/debug/shit-helper"));
        assert!(snip.contains("target/release/shit-helper"));
        assert!(snip.contains(".cargo/bin/shit-helper"));
    }

    #[test]
    fn nixos_snippet_renders_extra_rules_block() {
        let snip = emit_sudoers_snippet(SudoersTarget::NixOS);
        assert!(snip.contains("security.sudo.extraRules"));
        assert!(snip.contains("users = [ "));
        assert!(snip.contains("options = [ \"NOPASSWD\" ]"));
        assert!(snip.contains("cap_sys_admin,cap_bpf,cap_perfmon+ep"));
    }

    #[test]
    fn target_parses_aliases() {
        use std::str::FromStr;
        assert_eq!(
            SudoersTarget::from_str("generic").unwrap(),
            SudoersTarget::Generic
        );
        assert_eq!(
            SudoersTarget::from_str("debian").unwrap(),
            SudoersTarget::Generic
        );
        assert_eq!(
            SudoersTarget::from_str("NixOS").unwrap(),
            SudoersTarget::NixOS
        );
        assert!(SudoersTarget::from_str("solaris").is_err());
    }

    #[test]
    fn discover_paths_includes_workspace_and_install_locations() {
        let paths = discover_helper_binary_paths();
        assert!(paths.iter().any(|p| p.ends_with("target/debug/shit-helper")));
        assert!(
            paths
                .iter()
                .any(|p| p.ends_with("target/release/shit-helper"))
        );
        assert!(paths.iter().any(|p| p.ends_with(".cargo/bin/shit-helper")));
        assert!(paths.iter().any(|p| p == &PathBuf::from("/usr/local/bin/shit-helper")));
    }
}
