[package]
name = "shit-capture"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
shit-proto = { workspace = true }
shit-planner = { workspace = true }
shit-store = { workspace = true }
nix = { workspace = true }
libc = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
blake3 = { workspace = true }

[dev-dependencies]
tempfile = "3.10"
