// SPDX-License-Identifier: AGPL-3.0-or-later

//! `shit service` — install/uninstall/start/stop/status across the four
//! supported service managers (launchd, systemd --user, runit, manual).
//!
//! Template files live under `packaging/`; we embed them with `include_str!`
//! and substitute `@@SHITD_BIN@@`, `@@CONFIG_PATH@@`, `@@LOG_PATH@@`, `@@LABEL@@`
//! at install time.

use anyhow::{Context, Result, bail};
use std::path::PathBuf;
use std::process::Command;

use crate::{config_home, home_dir};

const LABEL: &str = "com.tenseleyflow.shit";

const LAUNCHD_PLIST: &str = include_str!("../../../packaging/launchd/shit.plist");
const SYSTEMD_UNIT: &str = include_str!("../../../packaging/systemd/shit.service");
const RUNIT_RUN: &str = include_str!("../../../packaging/runit/run");
const FREEBSD_LAUNCHER: &str = include_str!("../../../packaging/freebsd-ports/shit-start.sh");

const DEFAULT_CONFIG_BODY: &str = "\
# shit daemon — generated by `shit service install`.
# Override fields here; absent fields fall back to built-in defaults.

# Service-managed mode pins the daemon up. Set > 0 to re-enable idle-down.
idle_timeout_secs = 0

log_level = \"info\"
";

#[derive(Debug, Clone, Copy)]
// variants are used on different cfg targets; suppress per-target dead-code noise
#[allow(dead_code)]
pub enum ServiceManager {
    Launchd,
    SystemdUser,
    Runit,
    Manual,
}

impl ServiceManager {
    // cfg-gated branches make clippy think the `return`s are needless.
    #[allow(clippy::needless_return)]
    pub fn detect() -> Self {
        #[cfg(target_os = "macos")]
        {
            return Self::Launchd;
        }
        #[cfg(target_os = "linux")]
        {
            if Command::new("systemctl")
                .args(["--user", "--version"])
                .output()
                .map(|o| o.status.success())
                .unwrap_or(false)
            {
                return Self::SystemdUser;
            }
            if Command::new("sv")
                .arg("--help")
                .output()
                .map(|o| o.status.success())
                .unwrap_or(false)
                || std::path::Path::new("/etc/runit/runsvdir/default").exists()
            {
                return Self::Runit;
            }
            return Self::Manual;
        }
        #[cfg(target_os = "freebsd")]
        {
            return Self::Manual;
        }
        #[cfg(not(any(target_os = "macos", target_os = "linux", target_os = "freebsd")))]
        {
            Self::Manual
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Launchd => "launchd",
            Self::SystemdUser => "systemd --user",
            Self::Runit => "runit",
            Self::Manual => "manual",
        }
    }
}

struct Subs {
    shitd_bin: PathBuf,
    config_path: PathBuf,
    log_path: PathBuf,
}

fn render(template: &str, s: &Subs) -> String {
    template
        .replace("@@SHITD_BIN@@", s.shitd_bin.to_str().unwrap_or(""))
        .replace("@@CONFIG_PATH@@", s.config_path.to_str().unwrap_or(""))
        .replace("@@LOG_PATH@@", s.log_path.to_str().unwrap_or(""))
        .replace("@@LABEL@@", LABEL)
}

fn locate_shitd_bin() -> Result<PathBuf> {
    let shit_bin = std::env::current_exe().context("current_exe")?;
    let parent = shit_bin
        .parent()
        .ok_or_else(|| anyhow::anyhow!("current_exe has no parent: {}", shit_bin.display()))?;
    let candidate = parent.join("shitd");
    if !candidate.exists() {
        bail!(
            "shitd binary not found at {} — install shit and shitd to the same directory",
            candidate.display()
        );
    }
    Ok(candidate)
}

fn ensure_config() -> Result<PathBuf> {
    let dir = config_home()?.join("shit");
    std::fs::create_dir_all(&dir)?;
    let path = dir.join("config.toml");
    if !path.exists() {
        std::fs::write(&path, DEFAULT_CONFIG_BODY)
            .with_context(|| format!("write {}", path.display()))?;
        println!("wrote default config at {}", path.display());
    }
    Ok(path)
}

fn state_log_path() -> Result<PathBuf> {
    if let Some(s) = std::env::var_os("XDG_STATE_HOME") {
        let p = PathBuf::from(s).join("shit");
        std::fs::create_dir_all(&p)?;
        return Ok(p.join("daemon.log"));
    }
    let p = home_dir()?.join(".local").join("state").join("shit");
    std::fs::create_dir_all(&p)?;
    Ok(p.join("daemon.log"))
}

fn subs() -> Result<Subs> {
    Ok(Subs {
        shitd_bin: locate_shitd_bin()?,
        config_path: ensure_config()?,
        log_path: state_log_path()?,
    })
}

fn launchd_plist_path() -> Result<PathBuf> {
    Ok(home_dir()?
        .join("Library")
        .join("LaunchAgents")
        .join(format!("{LABEL}.plist")))
}

fn systemd_unit_path() -> Result<PathBuf> {
    Ok(config_home()?
        .join("systemd")
        .join("user")
        .join("shit.service"))
}

fn runit_service_path() -> Result<PathBuf> {
    Ok(config_home()?.join("service").join("shit").join("run"))
}

fn freebsd_launcher_path() -> Result<PathBuf> {
    Ok(config_home()?.join("shit").join("start-daemon.sh"))
}

pub fn install() -> Result<()> {
    let mgr = ServiceManager::detect();
    let s = subs()?;
    println!("detected service manager: {}", mgr.as_str());
    println!("  shitd: {}", s.shitd_bin.display());
    println!("  config: {}", s.config_path.display());
    println!("  log: {}", s.log_path.display());

    match mgr {
        ServiceManager::Launchd => install_launchd(&s),
        ServiceManager::SystemdUser => install_systemd(&s),
        ServiceManager::Runit => install_runit(&s),
        ServiceManager::Manual => install_manual(&s),
    }
}

pub fn uninstall() -> Result<()> {
    match ServiceManager::detect() {
        ServiceManager::Launchd => uninstall_launchd(),
        ServiceManager::SystemdUser => uninstall_systemd(),
        ServiceManager::Runit => uninstall_runit(),
        ServiceManager::Manual => uninstall_manual(),
    }
}

pub fn start() -> Result<()> {
    match ServiceManager::detect() {
        ServiceManager::Launchd => {
            sh(&["launchctl", "kickstart", &format!("gui/{}/{LABEL}", uid())])
        }
        ServiceManager::SystemdUser => sh(&["systemctl", "--user", "start", "shit.service"]),
        ServiceManager::Runit => sh(&["sv", "up", "shit"]),
        ServiceManager::Manual => {
            println!("manual service mode — run the daemon yourself:");
            println!("  bash {}", freebsd_launcher_path()?.display());
            Ok(())
        }
    }
}

pub fn stop() -> Result<()> {
    match ServiceManager::detect() {
        ServiceManager::Launchd => sh(&[
            "launchctl",
            "kill",
            "TERM",
            &format!("gui/{}/{LABEL}", uid()),
        ]),
        ServiceManager::SystemdUser => sh(&["systemctl", "--user", "stop", "shit.service"]),
        ServiceManager::Runit => sh(&["sv", "down", "shit"]),
        ServiceManager::Manual => {
            println!("manual service mode — kill the daemon yourself: pkill shitd");
            Ok(())
        }
    }
}

pub fn status() -> Result<()> {
    let mgr = ServiceManager::detect();
    println!("service manager: {}", mgr.as_str());
    match mgr {
        ServiceManager::Launchd => {
            let _ = sh(&["launchctl", "print", &format!("gui/{}/{LABEL}", uid())]);
        }
        ServiceManager::SystemdUser => {
            let _ = sh(&["systemctl", "--user", "status", "shit.service"]);
        }
        ServiceManager::Runit => {
            let _ = sh(&["sv", "status", "shit"]);
        }
        ServiceManager::Manual => {
            println!("(manual mode — use `pgrep shitd` to check)");
        }
    }
    Ok(())
}

fn install_launchd(s: &Subs) -> Result<()> {
    let plist = launchd_plist_path()?;
    if let Some(parent) = plist.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&plist, render(LAUNCHD_PLIST, s))?;
    println!("wrote {}", plist.display());
    sh(&[
        "launchctl",
        "bootstrap",
        &format!("gui/{}", uid()),
        plist.to_str().unwrap(),
    ])?;
    println!("loaded into launchd; auto-starts on login");
    Ok(())
}

fn uninstall_launchd() -> Result<()> {
    let plist = launchd_plist_path()?;
    let _ = sh(&[
        "launchctl",
        "bootout",
        &format!("gui/{}", uid()),
        plist.to_str().unwrap_or(""),
    ]);
    if plist.exists() {
        std::fs::remove_file(&plist)?;
        println!("removed {}", plist.display());
    }
    Ok(())
}

fn install_systemd(s: &Subs) -> Result<()> {
    let unit = systemd_unit_path()?;
    if let Some(parent) = unit.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&unit, render(SYSTEMD_UNIT, s))?;
    println!("wrote {}", unit.display());
    sh(&["systemctl", "--user", "daemon-reload"])?;
    sh(&["systemctl", "--user", "enable", "shit.service"])?;
    println!("enabled shit.service; start with `shit service start`");
    Ok(())
}

fn uninstall_systemd() -> Result<()> {
    let _ = sh(&["systemctl", "--user", "disable", "--now", "shit.service"]);
    let unit = systemd_unit_path()?;
    if unit.exists() {
        std::fs::remove_file(&unit)?;
        println!("removed {}", unit.display());
    }
    let _ = sh(&["systemctl", "--user", "daemon-reload"]);
    Ok(())
}

fn install_runit(s: &Subs) -> Result<()> {
    let run = runit_service_path()?;
    if let Some(parent) = run.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&run, render(RUNIT_RUN, s))?;
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(&run, std::fs::Permissions::from_mode(0o755))?;
    println!("wrote {}", run.display());
    println!(
        "to activate: ensure your runit runsvdir watches {}",
        run.parent().unwrap().parent().unwrap().display()
    );
    Ok(())
}

fn uninstall_runit() -> Result<()> {
    let run = runit_service_path()?;
    if let Some(dir) = run.parent()
        && dir.exists()
    {
        std::fs::remove_dir_all(dir)?;
        println!("removed {}", dir.display());
    }
    Ok(())
}

fn install_manual(s: &Subs) -> Result<()> {
    let launcher = freebsd_launcher_path()?;
    if let Some(parent) = launcher.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&launcher, render(FREEBSD_LAUNCHER, s))?;
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(&launcher, std::fs::Permissions::from_mode(0o755))?;
    println!("wrote {}", launcher.display());
    println!("manual service mode — start with `shit service start`");
    Ok(())
}

fn uninstall_manual() -> Result<()> {
    let launcher = freebsd_launcher_path()?;
    if launcher.exists() {
        std::fs::remove_file(&launcher)?;
        println!("removed {}", launcher.display());
    }
    Ok(())
}

fn sh(argv: &[&str]) -> Result<()> {
    let mut cmd = Command::new(argv[0]);
    if argv.len() > 1 {
        cmd.args(&argv[1..]);
    }
    let status = cmd
        .status()
        .with_context(|| format!("spawn {}", argv.join(" ")))?;
    if !status.success() {
        bail!("{} exited {status}", argv.join(" "));
    }
    Ok(())
}

fn uid() -> u32 {
    // SAFETY: getuid always succeeds.
    unsafe { libc::getuid() }
}
